export const translations = {
  en: {
    posTerminal: "POS Terminal",
    inventoryCatalog: "Inventory",
    analyticsDashboard: "Analytics",
    settings: "Settings",
    activeOperator: "Active Operator",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    searchPlaceholder: "Search products or scan barcode (SKU)...",
    scanSku: "Scan SKU",
    all: "All",
    outOfStock: "OUT",
    unitsLeft: "left",
    units: "units",
    activeTransaction: "Active Transaction",
    cartEmpty: "Cart is currently empty.",
    subtotal: "Subtotal",
    discount: "Discount (%)",
    tax: "VAT",
    total: "Total",
    cash: "Cash",
    card: "Card",
    mobile: "Mobile",
    cashReceived: "Cash Received",
    changeDue: "Change Due",
    completeCheckout: "Complete Checkout",
    inventoryTitle: "Inventory Catalog",
    inventorySub: "Manage products, pricing, stock levels, and barcode details.",
    addNewProduct: "Add New Product",
    searchInventory: "Search by name or SKU/Barcode...",
    showLowStock: "Show Low Stock Only",
    sku: "SKU/Barcode",
    productName: "Product Name",
    category: "Category",
    costPrice: "Cost Price",
    sellingPrice: "Selling Price",
    stockLevel: "Stock Level",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    saveProduct: "Save Product",
    cancel: "Cancel",
    grossRevenue: "Gross Revenue",
    dailyReport: "Daily Report",
    monthlyReport: "Monthly Report",
    annualReport: "Annual Report",
    allTime: "All Time",
    netProfit: "Net Profit",
    transactionsCount: "Transactions",
    catalogSKU: "Catalog SKU count",
    salesArchive: "Sales Archive & Transaction Log",
    noTransactions: "No transaction records available.",
    itemBreakdown: "Item Breakdown",
    reprintInvoice: "Re-print Invoice",
    categoryDemand: "Category Demand",
    paymentBreakdown: "Payment breakdown",
    cashSales: "Cash Sales",
    cardSales: "Card Sales",
    mobileSales: "Mobile Sales",
    storeProfile: "Store Profile",
    storeName: "Store Name",
    storeAddress: "Store Address",
    storePhone: "Store Phone",
    taxRate: "Tax Rate (%)",
    vatTRN: "VAT Registration Number (TRN - 15 digits)",
    currencySymbol: "Currency Symbol",
    receiptFooter: "Receipt Footer Notice",
    saveConfiguration: "Save Store Configuration",
    manageOperators: "Manage Operators",
    addOperator: "Add Operator",
    username: "Username",
    fullName: "Full Name",
    role: "Role",
    add: "Add",
    dbBackupUtility: "Database Backup & Utility",
    dbBackupSub: "Export your inventory catalogue, historical logs, and settings to a JSON backup file.",
    exportDB: "Export JSON Database",
    importDB: "Import JSON Database",
    systemDiagnostics: "System Diagnostics & Reset",
    systemDiagnosticsSub: "If you run into database synchronization errors, factory reset the database.",
    factoryReset: "Factory Reset Application",
    appSpecs: "Application Specs",
    awaitingTerminal: "Awaiting Mada Terminal Response",
    swipeOrPlace: "Please swipe/insert card or place mobile phone on card reader...",
    zatcaComplianceHeader: "E-Invoice Compliance (ZATCA)",
    transactionSuccessful: "Transaction Successful",
    printReceipt: "Print Receipt",
    done: "Done",
    arabic: "العربية",
    english: "English",
    low: "Low"
  },
  ar: {
    posTerminal: "شاشة الكاشير",
    inventoryCatalog: "إدارة المخزون",
    analyticsDashboard: "التقارير والإحصائيات",
    settings: "إعدادات النظام",
    activeOperator: "الكاشير النشط",
    lightMode: "الوضع النهاري",
    darkMode: "الوضع الليلي",
    searchPlaceholder: "ابحث عن منتج أو امسح الباركود...",
    scanSku: "مسح الكود",
    all: "الكل",
    outOfStock: "نفذ",
    unitsLeft: "متبقي",
    units: "حبة",
    activeTransaction: "العملية الحالية",
    cartEmpty: "سلة المشتريات فارغة.",
    subtotal: "الإجمالي الخاضع للضريبة",
    discount: "الخصم (%)",
    tax: "ضريبة القيمة المضافة",
    total: "الإجمالي شامل الضريبة",
    cash: "نقدي",
    card: "بطاقة مدى",
    mobile: "جوال / دفع إلكتروني",
    cashReceived: "المبلغ المستلم",
    changeDue: "المبلغ المتبقي",
    completeCheckout: "إتمام عملية الدفع",
    inventoryTitle: "دليل المنتجات والمخازن",
    inventorySub: "إدارة المنتجات، التسعير، مستويات المخزون، وتفاصيل الباركود.",
    addNewProduct: "إضافة منتج جديد",
    searchInventory: "ابحث بالاسم أو الباركود...",
    showLowStock: "عرض المخزون المنخفض فقط",
    sku: "الباركود / SKU",
    productName: "اسم المنتج",
    category: "الفئة",
    costPrice: "سعر التكلفة",
    sellingPrice: "سعر البيع",
    stockLevel: "كمية المخزون",
    actions: "العمليات",
    edit: "تعديل",
    delete: "حذف",
    saveProduct: "حفظ المنتج",
    cancel: "إلغاء",
    grossRevenue: "إجمالي المبيعات",
    dailyReport: "تقرير اليوم",
    monthlyReport: "التقرير الشهري",
    annualReport: "التقرير السنوي",
    allTime: "الكل",
    netProfit: "صافي الأرباح",
    transactionsCount: "عدد الفواتير",
    catalogSKU: "إجمالي المنتجات المسجلة",
    salesArchive: "سجل العمليات والأرشيف",
    noTransactions: "لا توجد أي فواتير مسجلة بعد.",
    itemBreakdown: "تفاصيل المنتجات",
    reprintInvoice: "إعادة طباعة الفاتورة",
    categoryDemand: "الطلب حسب الفئة",
    paymentBreakdown: "طرق الدفع",
    cashSales: "المبيعات النقدية",
    cardSales: "مبيعات مدى",
    mobileSales: "مبيعات الجوال",
    storeProfile: "بيانات المنشأة",
    storeName: "اسم المتجر",
    storeAddress: "العنوان",
    storePhone: "رقم الهاتف",
    taxRate: "نسبة الضريبة (%)",
    vatTRN: "الرقم الضريبي (15 خانة)",
    currencySymbol: "العملة",
    receiptFooter: "ملاحظة أسفل الفاتورة",
    saveConfiguration: "حفظ الإعدادات",
    manageOperators: "إدارة المستخدمين والكاشيرات",
    addOperator: "إضافة مستخدم جديد",
    username: "اسم المستخدم",
    fullName: "الاسم الكامل",
    role: "الصلاحية",
    add: "إضافة",
    dbBackupUtility: "نسخ قاعدة البيانات احتياطياً",
    dbBackupSub: "تصدير المخزون الحالي وسجلات المبيعات والإعدادات إلى ملف خارجي.",
    exportDB: "تصدير قاعدة البيانات",
    importDB: "استيراد قاعدة البيانات",
    systemDiagnostics: "فحص وإعادة ضبط النظام",
    systemDiagnosticsSub: "إذا واجهت أخطاء في المزامنة، يمكنك تهيئة قاعدة البيانات بالكامل.",
    factoryReset: "إعادة ضبط المصنع",
    appSpecs: "مواصفات التطبيق",
    awaitingTerminal: "جاري الاتصال بجهاز مدى للشبكة",
    swipeOrPlace: "برجاء تمرير البطاقة أو وضع الجوال على قارئ الشبكة...",
    zatcaComplianceHeader: "فاتورة ضريبية مبسطة (هيئة الزكاة)",
    transactionSuccessful: "تمت العملية بنجاح",
    printReceipt: "طباعة الفاتورة",
    done: "موافق",
    arabic: "العربية",
    english: "English",
    low: "منخفض"
  }
};
